<h3>creating an array using numpy module</h3>

In [1]:
import array
a1=array.array('i',[11,22,33,44])
print(type(a1))

<class 'array.array'>


In [4]:
#creating an array using numpy module
mat=[[2,4,6,8],[3,5,7,9],[12,14,16,18],[11,13,15,17]]
#print(type(mat))
mat[1][0]

3

In [6]:
#multiplying array element
mat[1][2]*2

14

In [8]:
for row in mat:
    for col in range(len(mat)):
        row[col]=row[col]*2
print(mat)

[[8, 16, 24, 32], [12, 20, 28, 36], [48, 56, 64, 72], [44, 52, 60, 68]]


<h3>printing array in the form of matrix($ pip3 install numpy) </h3>

In [1]:
#printing array in the form of matrix($ pip3 install numpy)
import numpy as np
matrix = np.array([[11,22,33],[44,55,66],[77,88,99]])
print(type(matrix))
print(matrix)

<class 'numpy.ndarray'>
[[11 22 33]
 [44 55 66]
 [77 88 99]]


<h3>array creation and its operation</h3>

In [3]:
import numpy as py
nums=py.array([11,22,33,44,55])
nums<20

array([ True, False, False, False, False])

In [8]:
import numpy as py
py.random.randint(20,50,8).reshape(4,2,1)


array([[[30],
        [34]],

       [[43],
        [20]],

       [[20],
        [35]],

       [[30],
        [38]]])

In [11]:
#array slicing
#array_object[row,col]
twoD_arr=py.array([[2,4,6,8,10],[1,3,5,7,9],[1,2,3,4,5]])
print(twoD_arr)
print("\n after slicing:")
twoD_arr[:3,:2]#.shape

[[ 2  4  6  8 10]
 [ 1  3  5  7  9]
 [ 1  2  3  4  5]]

 after slicing:


array([[2, 4],
       [1, 3],
       [1, 2]])

<h3>creating array with different type</h3>

In [12]:
np.array([[1,2,3],['a','b','c']])

array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U21')

In [17]:
threeD_arr=py.array([
    [[2,4,6,8,10],[1,3,5,7,9]],
    [[1,2,3,4,5],[2,5,3,4,2]],
    [[2,3,2,5,8],[2,4,6,8,1]]
])
print(threeD_arr)
print(threeD_arr[0,1,2])
print((threeD_arr).size)
print(threeD_arr.reshape(3,2,5))

[[[ 2  4  6  8 10]
  [ 1  3  5  7  9]]

 [[ 1  2  3  4  5]
  [ 2  5  3  4  2]]

 [[ 2  3  2  5  8]
  [ 2  4  6  8  1]]]
5
30
[[[ 2  4  6  8 10]
  [ 1  3  5  7  9]]

 [[ 1  2  3  4  5]
  [ 2  5  3  4  2]]

 [[ 2  3  2  5  8]
  [ 2  4  6  8  1]]]


In [22]:
twoD_arr=py.array([[2,4,6,8,10],[1,3,5,7,9],[1,2,3,4,5]])
#2*twoD_arr
# @(product fo the matrix)
twoD_arr1=py.array([[2,4,6,8,10],[1,3,5,7,9],[1,2,3,4,5]])
twoD_arr2=py.array([[2,4,6,8,10],[1,3,5,7,9],[1,2,3,4,5]])

In [24]:
num=np.array([[1,2,3],[4,5,6],[7,8,9]])
#num.shape
num.diagonal()

array([1, 5, 9])

In [25]:
#get a 1-d array of all enteries
num.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
#calculate the sum of all enteries
num.sum()

np.int64(45)

In [27]:
num.min()

np.int64(1)

In [28]:
num.max()

np.int64(9)

<h3>stacking and shaping arrays:two arrays can be stacked vertically using np.vstack() </h3>

In [32]:
num1=np.array([[1,2,3],[4,5,6],[7,8,9]])
num2=np.array([[3,4,7],[4,8,6],[2,5,9]])
np.hstack((num1,num2))
np.vstack((num1,num2))


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 4, 7],
       [4, 8, 6],
       [2, 5, 9]])

<h3>arange() functio in numpy</h3>

In [34]:
import numpy
seq=numpy.arange(1,11,3)
seq

array([ 1,  4,  7, 10])

<h3>create a 3x3 array named first_mat that include 3 through 11 by using arange() function and reshape the array object by 3x2x2</h3>

In [38]:
first_mat=py.array([
    [[2,4,6,8,10],[1,3,5,7,9]],
    [[1,2,3,4,5],[2,5,3,4,2]],
    [[2,3,2,5,8],[2,4,6,8,1]]
])
numbers=np.arange(3,12)
first_mat=numbers.reshape(3,3,1)
print(first_mat)

[[[ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]]]


<h3>square every entry in first matrix using ** operator and save result in an array named second_mat</h3>

In [39]:
num1=np.array([[1,2,3],[4,5,6],[7,8,9]])
second_mat=num1**2
print(second_mat)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
