#### (1)Creating an array using numpy module

In [3]:
import array
a1 = array.array('i',[11,22,33,44])
print(type(a1))

<class 'array.array'>


In [5]:
mat = [[2,4,6,8],[3,5,7,9],[12,14,16,18],[11,13,15,17]]
print(type(mat))
mat[1][3]

<class 'list'>


9

#### (2)Multiplying array element

for row in mat:
    for col in range(len(mat)):
        row[col] = row[col] *2

#### (3) Printing array in the form of matrix ($ pip3 intall numpy)

In [1]:
import numpy as np
matrix = np.array([[11,22,33],[44,55,66],[77,88,99]])
print(type(matrix))
print(matrix)

<class 'numpy.ndarray'>
[[11 22 33]
 [44 55 66]
 [77 88 99]]


<h1>Array creation and its opeation</h1>

In [3]:
import numpy as py
Nums = py.array([11,22,33,44,55])
Nums<20
# Nums>15
#Nums != 10

array([ True, False, False, False, False])

In [9]:
import numpy as py
a3 = py.random.randint(1,10,6)
print(a3)

[4 8 1 6 1 2]


In [10]:
a3 = py.random.randint(1,10,6).reshape(2,3,1)
print(a3.ndim)

3


In [11]:
TwoD_arr = py.array([[2,4,6,8,10],[1,3,5,7,9],[1,2,3,4,5]])
print(TwoD_arr)
print("\n After slicing:")
TwoD_arr[:3,:2].shape

[[ 2  4  6  8 10]
 [ 1  3  5  7  9]
 [ 1  2  3  4  5]]

 After slicing:


(3, 2)

In [12]:
matrix = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(matrix)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [13]:
matrix = np.array([[1,1,1],[1,1,1],[1,1,1]])
2*matrix

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [15]:

matrix1 = np.array([[1,1,1],[1,1,1],[1,1,1],[1,1,1]])
matrix2 = np.array([[1,1,1],[1,1,1],[1,1,1],[1,1,1]])
matrix @ matrix

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

#### (7)Stacking and shaping Arrays: Two arrays can be

In [16]:
matrix1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
matrix2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

np.hstack((matrix1,matrix2))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [13, 14, 15],
        [16, 17, 18]]])

#### (1)Create a 3 x 3 array named frist_matrix that inclides the numbers 3 through 11 by using arange() function and reshape the array object by 3x2x2

In [19]:
frist_mat = py.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
numbers= np.arange(3,12)
frist_mat=numbers.reshape(3,3,1)
print(frist_mat)

[[[ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]]]


#### (5) Stack frist_matrix on top of second_matrix and save the resulits in ana array named thrid_matrix 